export const countries = {
    "USA": {
      "California": ["Los Angeles", "San Francisco", "San Diego"],
      "Texas": ["Houston", "Austin", "Dallas"],
      "New York": ["New York City", "Buffalo", "Rochester"],
      "Florida": ["Miami", "Orlando", "Tampa"],
      "Illinois": ["Chicago", "Springfield", "Naperville"],
    },
    "Canada": {
      "Ontario": ["Toronto", "Ottawa", "Mississauga"],
      "Quebec": ["Montreal", "Quebec City", "Laval"],
      "British Columbia": ["Vancouver", "Victoria", "Richmond"],
      "Alberta": ["Calgary", "Edmonton", "Red Deer"],
      "Manitoba": ["Winnipeg", "Brandon", "Steinbach"],
    },
    "India": {
      "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"],
      "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro"],
      "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
      "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"],
      "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
      "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
      "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
      "Haryana": ["Gurgaon", "Faridabad", "Panipat", "Ambala", "Yamunanagar"],
      "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan"],
      "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"],
      "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum"],
      "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur"],
      "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
      "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
      "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul"],
      "Meghalaya": ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara"],
      "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Serchhip"],
      "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"],
      "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Puri"],
      "Punjab": ["Amritsar", "Ludhiana", "Jalandhar", "Patiala", "Bathinda"],
      "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Ajmer", "Bikaner"],
      "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Singtam"],
      "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
      "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar"],
      "Tripura": ["Agartala", "Udaipur", "Kailashahar", "Dharmanagar", "Ambassa"],
      "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi"],
      "Uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur"],
      "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"],
    },
    "Australia": {
      "New South Wales": ["Sydney", "Newcastle", "Wollongong"],
      "Victoria": ["Melbourne", "Geelong", "Ballarat"],
      "Queensland": ["Brisbane", "Gold Coast", "Cairns"],
      "Western Australia": ["Perth", "Fremantle", "Bunbury"],
      "South Australia": ["Adelaide", "Mount Gambier", "Gawler"],
    },
    "United Kingdom": {
      "England": ["London", "Manchester", "Birmingham"],
      "Scotland": ["Edinburgh", "Glasgow", "Aberdeen"],
      "Wales": ["Cardiff", "Swansea", "Newport"],
      "Northern Ireland": ["Belfast", "Derry", "Lisburn"],
    },
    "Germany": {
      "Bavaria": ["Munich", "Nuremberg", "Augsburg"],
      "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund"],
      "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe"],
      "Hesse": ["Frankfurt", "Wiesbaden", "Darmstadt"],
      "Saxony": ["Dresden", "Leipzig", "Chemnitz"],
    },
    "France": {
      "Île-de-France": ["Paris", "Boulogne-Billancourt", "Saint-Denis"],
      "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon"],
      "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne"],
      "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers"],
      "Occitanie": ["Toulouse", "Montpellier", "Nîmes"],
    },
    "China": {
      "Beijing": ["Beijing"],
      "Shanghai": ["Shanghai"],
      "Guangdong": ["Guangzhou", "Shenzhen", "Dongguan"],
      "Zhejiang": ["Hangzhou", "Ningbo", "Wenzhou"],
      "Jiangsu": ["Nanjing", "Suzhou", "Wuxi"],
    },
    "Japan": {
      "Tokyo": ["Tokyo"],
      "Osaka": ["Osaka"],
      "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara"],
      "Aichi": ["Nagoya"],
      "Hokkaido": ["Sapporo"],
    },
    "Brazil": {
      "São Paulo": ["São Paulo", "Campinas", "Santos"],
      "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Petrópolis"],
      "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista"],
      "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem"],
      "Paraná": ["Curitiba", "Londrina", "Maringá"],
    },
    "Russia": {
      "Moscow": ["Moscow"],
      "Saint Petersburg": ["Saint Petersburg"],
      "Novosibirsk Oblast": ["Novosibirsk"],
      "Sverdlovsk Oblast": ["Yekaterinburg"],
      "Nizhny Novgorod Oblast": ["Nizhny Novgorod"],
    },
    "South Africa": {
      "Gauteng": ["Johannesburg", "Pretoria", "Midrand"],
      "Western Cape": ["Cape Town", "Stellenbosch", "Paarl"],
      "KwaZulu-Natal": ["Durban", "Pietermaritzburg", "Pinetown"],
      "Eastern Cape": ["Port Elizabeth", "East London", "Grahamstown"],
      "Free State": ["Bloemfontein", "Welkom", "Bethlehem"],
    },
  };